### ISSUE TITLE
About VISAM

### ISSUE THREAD

**Issue by wzj52501** [BingfengYan/MOTSAM#1]
Does the current project provide a combination of MOTRv2 and Segment Anything? It seems that the repository is completely forked from https://github.com/megvii-research/MOTRv2 except for thirdparty/segment-anything.

**Comment by fengxiuyaun** [comment]
I apologize for causing you any misunderstanding.
1. this only track and segment person, not anything.
2. This code was forked from MOTRv2 because our code has not been released. However, in the [submit.py]file, only one modification was made.
